### ISSUE TITLE
Placing item in item/weapon rack rerolls the modifier.

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [Jofairden/EvenMoreModifiers#15] opened 2018-04-25 06:03 UTC
Version of mod: 0.0.10.7
Title says it all. If weapon, armor or accessory is placed in weapon or item rack, modifier will be rerolled.
I don't know, if there's any other tiles that also can cause this.

**Comment by Jofairden** [comment] 2018-04-25 06:04
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/Jofairden/EvenMoreModifiers/issues/9 (Items should be able to opt-out from rolling modifiers), and https://github.com/Jofairden/EvenMoreModifiers/issues/5 (Modifiers issues).

**Comment by Jofairden** [comment] 2018-04-27 11:12
This actually was intended, because armors couldn't be rolled at the tinkerer before. Now that a hack to allow this in place, this behaviour can be removed. I think I'll have items roll when they are dropped by mobs instead.

**Comment by Jofairden** [comment] 2018-09-18 20:03
Should be fixed these days, except that you will still lose your modifiers. Unfortunately nothing can be done about it at this time.

**Closed as completed by Jofairden** 2018-09-18 20:03 UTC
Labels: bug
